version: '3.3'
services:
  db:
    container_name: db
    image: mysql:8.0.30
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'library'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'r3Dk7jcPBsSNtoTYxhGX'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'r3Dk7jcPBsSNtoTYxhGX'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '9999:3306'
    expose:
      # Opens port 3306 on the container
      - '9999'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: